apiVersion: v1
kind: ConfigMap
metadata:
  name: test-env
  namespace: default
data:
  coins: "1000000000000000utia"
  chainid: "test"
  keyring_backend: "test"
  validator_stake: "5000000000utia"
  evm_address: "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488"
